<?php 

$language_id = 2;
foreach($data['languages'] as $language) {
	if($language['language_id'] != 1) {
		$language_id = $language['language_id'];
	}
}

$output = array();
$output["lookbook_module"] = array (
  1 => 
  array (
    'title' => 
    array (
      1 => 'Look Book',
      $language_id => 'Look Book',
    ),
    'html' => 
    array (
      1 => '&lt;div id=&quot;tt-pageContent&quot;&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;AS CAROUSEL SLIDER&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-slider-lookbook arrow-location-center row tt-dots-absolute slick-animated-show-js&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-01.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 35%; left: 54%;&quot; data-top=&quot;35&quot; data-left=&quot;54&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;
                      &lt;span class=&quot;new-price&quot;&gt;$14&lt;/span&gt;
                      &lt;span class=&quot;old-price&quot;&gt;$24&lt;/span&gt;
                    &lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 57%; left: 48%;&quot; data-top=&quot;57&quot; data-left=&quot;48&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-02.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 39%; left: 44%;&quot; data-top=&quot;39&quot; data-left=&quot;44&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-03.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 47%; left: 45%;&quot; data-top=&quot;47&quot; data-left=&quot;45&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 41%; left: 55%;&quot; data-top=&quot;41&quot; data-left=&quot;55&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid-custom container-fluid-custom-mobile-padding&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;WITH MASONRY LAYOUT&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-lookbook-masonry&quot;&gt;
        &lt;div class=&quot;tt-lookbook-init tt-grid-col-3 tt-add-item&quot;&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-10.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 79%; left: 37%;&quot; data-top=&quot;79&quot; data-left=&quot;37&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-11.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 22%; left: 49%;&quot; data-top=&quot;22&quot; data-left=&quot;49&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 55%; left: 34%;&quot; data-top=&quot;55&quot; data-left=&quot;34&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-12.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 40%; left: 40%;&quot; data-top=&quot;40&quot; data-left=&quot;40&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-13.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 35%; left: 61%;&quot; data-top=&quot;35&quot; data-left=&quot;61&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 40%; left: 27%;&quot; data-top=&quot;40&quot; data-left=&quot;27&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-14.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 47%; left: 67%;&quot; data-top=&quot;47&quot; data-left=&quot;67&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-15.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 37%; left: 47%;&quot; data-top=&quot;37&quot; data-left=&quot;47&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid-custom container-fluid-custom-mobile-padding&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;AS GRID + SLIDER&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-carousel-lookbook arrow-location-center row tt-dots-absolute slick-animated-show-js&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-17.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 30%; left: 50%;&quot; data-top=&quot;30&quot; data-left=&quot;50&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 61%; left: 48%;&quot; data-top=&quot;61&quot; data-left=&quot;48&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-07.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 34%; left: 57%;&quot; data-top=&quot;34&quot; data-left=&quot;57&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 78%; left: 44%;&quot; data-top=&quot;78&quot; data-left=&quot;44&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-18.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 22%; left: 27%;&quot; data-top=&quot;22&quot; data-left=&quot;27&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 34%; left: 58%;&quot; data-top=&quot;34&quot; data-left=&quot;58&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-16.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 55%; left: 70%;&quot; data-top=&quot;55&quot; data-left=&quot;70&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 25%; left: 41%;&quot; data-top=&quot;25&quot; data-left=&quot;41&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-19.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 27%; left: 47%;&quot; data-top=&quot;27&quot; data-left=&quot;47&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 69%; left: 41%;&quot; data-top=&quot;69&quot; data-left=&quot;41&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-09.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 29%; left: 47%;&quot; data-top=&quot;29&quot; data-left=&quot;47&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;',
      $language_id => '&lt;div id=&quot;tt-pageContent&quot;&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;AS CAROUSEL SLIDER&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-slider-lookbook arrow-location-center row tt-dots-absolute slick-animated-show-js&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-01.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 35%; left: 54%;&quot; data-top=&quot;35&quot; data-left=&quot;54&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;
                      &lt;span class=&quot;new-price&quot;&gt;$14&lt;/span&gt;
                      &lt;span class=&quot;old-price&quot;&gt;$24&lt;/span&gt;
                    &lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 57%; left: 48%;&quot; data-top=&quot;57&quot; data-left=&quot;48&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-02.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 39%; left: 44%;&quot; data-top=&quot;39&quot; data-left=&quot;44&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-03.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 47%; left: 45%;&quot; data-top=&quot;47&quot; data-left=&quot;45&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 41%; left: 55%;&quot; data-top=&quot;41&quot; data-left=&quot;55&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid-custom container-fluid-custom-mobile-padding&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;WITH MASONRY LAYOUT&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-lookbook-masonry&quot;&gt;
        &lt;div class=&quot;tt-lookbook-init tt-grid-col-3 tt-add-item&quot;&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-10.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 79%; left: 37%;&quot; data-top=&quot;79&quot; data-left=&quot;37&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-11.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 22%; left: 49%;&quot; data-top=&quot;22&quot; data-left=&quot;49&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 55%; left: 34%;&quot; data-top=&quot;55&quot; data-left=&quot;34&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-12.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 40%; left: 40%;&quot; data-top=&quot;40&quot; data-left=&quot;40&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-13.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 35%; left: 61%;&quot; data-top=&quot;35&quot; data-left=&quot;61&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 40%; left: 27%;&quot; data-top=&quot;40&quot; data-left=&quot;27&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-14.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 47%; left: 67%;&quot; data-top=&quot;47&quot; data-left=&quot;67&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class=&quot;element-item&quot;&gt;
            &lt;div class=&quot;tt-lookbook&quot;&gt;
              &lt;img src=&quot;image/catalog/wokiee/lookbook/lookbook-15.jpg&quot; alt=&quot;&quot;&gt;
              &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 37%; left: 47%;&quot; data-top=&quot;37&quot; data-left=&quot;47&quot;&gt;
                &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
                &lt;div class=&quot;tt-content-parent&quot;&gt;
                  &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                    &lt;div class=&quot;tt-img&quot;&gt;
                      &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;tt-description&quot;&gt;
                      &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket&lt;/a&gt;&lt;/h2&gt;
                      &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                      &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class=&quot;container-indent&quot;&gt;
    &lt;div class=&quot;container-fluid-custom container-fluid-custom-mobile-padding&quot;&gt;
      &lt;div class=&quot;tt-block-title&quot;&gt;
        &lt;h1 class=&quot;tt-title&quot;&gt;DISPLAY YOUR LOOKBOOK&lt;/h1&gt;
        &lt;div class=&quot;tt-description&quot;&gt;AS GRID + SLIDER&lt;/div&gt;
      &lt;/div&gt;
      &lt;div class=&quot;tt-carousel-lookbook arrow-location-center row tt-dots-absolute slick-animated-show-js&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-17.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 30%; left: 50%;&quot; data-top=&quot;30&quot; data-left=&quot;50&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 61%; left: 48%;&quot; data-top=&quot;61&quot; data-left=&quot;48&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-07.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 34%; left: 57%;&quot; data-top=&quot;34&quot; data-left=&quot;57&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 78%; left: 44%;&quot; data-top=&quot;78&quot; data-left=&quot;44&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-18.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 22%; left: 27%;&quot; data-top=&quot;22&quot; data-left=&quot;27&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 34%; left: 58%;&quot; data-top=&quot;34&quot; data-left=&quot;58&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-16.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 55%; left: 70%;&quot; data-top=&quot;55&quot; data-left=&quot;70&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 25%; left: 41%;&quot; data-top=&quot;25&quot; data-left=&quot;41&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-19.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 27%; left: 47%;&quot; data-top=&quot;27&quot; data-left=&quot;47&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 69%; left: 41%;&quot; data-top=&quot;69&quot; data-left=&quot;41&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div&gt;
          &lt;div class=&quot;tt-lookbook&quot;&gt;
            &lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/lookbook/lookbook-09.jpg&quot; alt=&quot;&quot;&gt;
            &lt;div class=&quot;tt-hotspot&quot; style=&quot;top: 29%; left: 47%;&quot; data-top=&quot;29&quot; data-left=&quot;47&quot;&gt;
              &lt;div class=&quot;tt-btn&quot;&gt;&lt;/div&gt;
              &lt;div class=&quot;tt-content-parent&quot;&gt;
                &lt;div class=&quot;tt-hotspot-content&quot;&gt;
                  &lt;a href=&quot;#&quot; class=&quot;tt-btn-close&quot;&gt;&lt;/a&gt;
                  &lt;div class=&quot;tt-img&quot;&gt;
                    &lt;a href=&quot;#&quot;&gt;&lt;img src=&quot;catalog/view/theme/wokiee/img/loader.svg&quot; data-src=&quot;image/catalog/wokiee/product/product-01-02.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;
                  &lt;/div&gt;
                  &lt;div class=&quot;tt-description&quot;&gt;
                    &lt;h2 class=&quot;tt-title&quot;&gt;&lt;a href=&quot;#&quot;&gt;Denim Boyfriend Trucker Jacket1&lt;/a&gt;&lt;/h2&gt;
                    &lt;div class=&quot;tt-price&quot;&gt;$124&lt;/div&gt;
                    &lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;ADD TO CART&lt;/a&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;',
    ),
  ),
); 

$this->model_setting_setting->editSetting( "lookbook_module", $output );	

?>